name: Matrix Artifacts Workflow

on:
  push:
    branches:
      - main

jobs:
  matrix-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: [job1, job2, job3] # Define your matrix
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Your Job
        run: echo "Running job for ${matrix.job_name}"

      - name: Create Artifact
        run: |
          mkdir -p artifacts/${{ matrix.job_name }}
          echo "This is artifact for ${matrix.job_name}" > artifacts/${{ matrix.job_name }}/artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.job_name }}
          path: artifacts/${{ matrix.job_name }}

  gather-artifacts:
    runs-on: ubuntu-latest
    needs: matrix-jobs # Ensure it runs after all matrix jobs
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: all-artifacts

      - name: Combine Artifacts
        run: |
          mkdir -p final-artifacts
          mv all-artifacts/* final-artifacts/

      - name: Upload Combined Artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-artifacts
          path: final-artifacts
