name: def check
on: 
 # schedule:
 # - cron: "* * * * *"
 workflow_dispatch:
  inputs:
   all_resources:
    description: "Would you like to defender scan for all resources?"
    required: true
    type: boolean
    default: false
   env_grp:
     description: please tri or pre or rls env group
     required: true
     type: choice
     default: ""
     options:
      - tri
      - pre
      - rls
jobs:
  defender-check:
    if: ${{ github.event_name == 'schedule' }}
    name: ${{ matrix.environment }}_MS defender scan for azure resources 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [tri,pre,rls] 
    environment: aig-ms-${{ matrix.environment }}-labff
    steps:
    - name: Run Defender for Cloud Scan for LA Resources only
      id: defender_scan_for_LA_resources
      run: |
        report_file="${{ matrix.environment }}_security_alerts_report.json"
        echo '[]' > $report_file
        echo "All security alerts have been collected in $report_file"
    - name: archive MS defender result
      uses: actions/upload-artifact@v3
      with:
       name: ${{ matrix.environment }}_azure_defender_cloud_results
       retention-days: 1
       path: | 
        ${{ matrix.environment }}_security_alerts_report.json

  defender-scancheck:
    if: ${{ github.event_name  == 'workflow_dispatch' }}
    name: ${{ github.event.inputs.env_grp }}_MS defender scan for azure_resources 
    runs-on: ubuntu-latest
    environment: aig-ms-${{ github.event.inputs.env_grp }}-labff
    steps:
    - name: Run Defender for Cloud Scan for LA Resources only
      id: defender_scan_for_LA_resources
      if: ${{ github.event.inputs.all_resources == 'false' }}
      run: |
        report_file="${{ github.event.inputs.env_grp }}_security_alerts_report.json"
        echo '[]' > $report_file
        echo "All security alerts have been collected in $report_file"

    - name: Run Defender for Cloud Scan for all Resources
      id: defender_scan_for_all_resources
      if: ${{ github.event.inputs.all_resources == 'true' }}
      run: |
        report_file="${{ github.event.inputs.env_grp }}_security_alerts_report.json"
        echo '[]' > $report_file
        echo "All security alerts have been collected in $report_file"

    - name: archive MS defender result
      uses: actions/upload-artifact@v3
      with:
       name: ${{ github.event.inputs.env_grp }}_azure_defender_cloud_results
       retention-days: 1
       path: | 
        ${{ github.event.inputs.env_grp }}_security_alerts_report.json

