name: docker image
on:
  workflow_dispatch: {}
jobs:
  dokcer_image:
    name: build docker image
    runs-on: windows-latest
    steps:
      - name: code checkout
        uses: actions/chechout@v1
      - name: docker setup 
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: docker image build
#         env:
#           REGISTRY: ghcr.io
#           OWNER: kishore
#           IMAGE_NAME: ${{ github.repository }}
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: Dockerfile
#           push: true
      - name: docker image build
        run: docker build -t " ${{ github.repository }}/kishore:1 "
      - name: image push to GHCR
        run: docker push ${{ github.repository }}/kishore:1
         
        
