name: check
on:
 workflow_dispatch:
   inputs:
    oss:
     description: "To perform OSS_CHECK_LIST with syft"
     type: boolean
    grype:
     description: "To check image vulnerability with grype"
     type: boolean
    ut:
     description: "To check coverage of UT"
     type: boolean

jobs:
  all-msv:
   name: all msv check from the main branch
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/main'
   steps:
    - name: chekcout
      uses: actions/checkout@master
    - name: install syft
      if: ${{ inputs.oss }}
      run: | 
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        syft ubuntu --scope all-layers -o spdx-json=sbom.spdx.json
  msv-base:
    name:  msv check from the individual msv branch
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - name: chekcout
      uses: actions/checkout@master
    - name: install syft
      if: ${{ inputs.oss }}
      run: |
        # check the msv code from the bracnh
        DIR_NAME=$(basename $(pwd))
        echo "Directory name is: $DIR_NAME"
        
        # Set the directory name as an output variable
        echo "dir_name=$DIR_NAME" >> $GITHUB_ENV
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        syft ubuntu --scope all-layers -o spdx-json=sbom.spdx.json
    
  
       
     
