on: 
 schedule:
   - cron: "* * * * *"
 workflow_dispatch:
   inputs:
    all_resources:
        description: "Would you like to defender scan for all resources?"
        required: true
        type: boolean
        default: true

jobs:
 hello1:
   runs-on: ubuntu-latest
   steps:
    - name: csasd
      uses: actions/checkout@v4

    - name: Run Defender for Cloud Scan for all resources
      id: defender_scan_for_all_resources
      if: ${{ github.event.inputs.all_resources == 'true' }}
      run: |
       echo "hello" > hello.txt
       hello=$(cat hello.txt)
       cat hello.txt
       echo "hello=$hello" >> $GITHUB_ENV

    - name: Run Defender for Cloud Scan for LA Resources only
      id: defender_scan_for_LA_resources
      if: ${{ github.event_name == 'schedule' }}
      run: |
       echo " helo"

 hello2:
   runs-on: ubuntu-latest
   needs: hello1
   steps:
    - name: csasd
      uses: actions/checkout@v4
    - run: |
       echo $hello > token
       cat token

  
