on: 
 workflow_dispatch: {}
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.sessiontoken.outputs.file }}
      output2: ${{ steps.sessiontoken.outputs.token }}
    steps:
      - id: sessiontoken
        run: |
           mkdir -p hello/1/2/3
           echo "sessionToken" > ./hello/1/2/3/hello.txt
           echo "token=$(cat ./hello/1/2/3/hello.txt)" >> "$GITHUB_OUTPUT"
           echo "::add-mask::sessiontoken=$(cat ./hello/1/2/3/hello.txt)" >> "$GITHUB_OUTPUT"
           cp ./hello/1/2/3/hello.txt $GITHUB_WORKSPACE/hello.txt
           echo "file=$(pwd)/hello/1/2/3/hello.txt" >> $GITHUB_OUTPUT
      - name: Cache the shared file
        uses: actions/cache@v3
        with:
          path: ./hello/1/2/3/hello.txt
          key: shared_file_cache
          restore-keys: |
            shared_file_cache
 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore cached file
        uses: actions/cache@v3
        with:
          path: ./hello/1/2/3/hello.txt
          key: shared_file_cache
          restore-keys: |
            shared_file_cache
      - name: Use the shared file
        run: |
          echo "Contents of the shared file:"
          cat ./hello/1/2/3/hello.txt





     

   
  
