on: 
 workflow_dispatch: {}
jobs:
  # job1:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     output1: ${{ steps.sessiontoken.outputs.sessiontoken }}
  #   steps:
  #     - id: sessiontoken
  #       run: |
  #          mkdir -p hello/1/2/3
  #          echo "sessionToken" > ./hello/1/2/3/hello.txt
  #          echo "sessiontoken=$(cat ./hello/1/2/3/hello.txt) " >> "$GITHUB_OUTPUT"
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.job1.outputs.output1}}
  #       run: echo "$OUTPUT1"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate secure content
        run: echo "Sensitive Data" > sensitive.txt
 
      - name: Set output
        id: set-output
        run: echo "::set-output name=sensitive_data::$(cat sensitive.txt)"
 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Get sensitive data from previous job
        run: echo "Sensitive data is: ${{ needs.job1.outputs.sensitive_data }}"
        env:
          SENSITIVE_DATA: ${{ needs.job1.outputs.sensitive_data }}
