on: 
 push:

jobs:
 hello1:
   runs-on: ubuntu-latest
   outputs:
      sessiontoken: ${{ steps.sessiontoken.outputs.test }}
   steps:

    - name: Run Defender for Cloud Scan for all resources
      id: sessiontoken
      # if: ${{ github.event.inputs.all_resources == 'true' }}
      run: |
       echo "hello" > hello.txt
       hello=$(cat hello.txt) >> "$GITHUB_OUTPUT"
        
 hello2:
   runs-on: ubuntu-latest
   needs: hello1
   steps:
      - env:
          sessiontoken: ${{needs.hello1.outputs.sessiontoken}}
        run: echo "$sessiontoken"
       

  
