on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.sessiontoken.outputs.sessiontoken }}
    steps:
      - id: sessiontoken
        run: |
           mkdir -p hello/1/2/3
           echo "sessionToken" > ./hello/1/2/3/hello.txt
           echo "sessiontoken=$(cat ./hello/1/2/3/hello.txt) " >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"
