on: 
 push:

jobs:
 hello1:
   runs-on: ubuntu-latest
   steps:

    - name: Run Defender for Cloud Scan for all resources
      id: defender_scan_for_all_resources
      # if: ${{ github.event.inputs.all_resources == 'true' }}
      run: |
       echo "hello" > hello.txt
       hello=$(cat hello.txt)
       cat hello.txt
       echo "hello" >> $HOME/work/hello.txt
       ls -la $HOME/work

 hello2:
   runs-on: ubuntu-latest
   needs: hello1
   steps:
    - run: |
       ls -la $HOME/work
       cat $HOME/work/hello.txt
       

  
