on: 
 workflow_dispatch: {}
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.sessiontoken.outputs.sessiontoken }}
      output2: ${{ steps.sessiontoken.outputs.token }}
    steps:
      - id: sessiontoken
        run: |
           mkdir -p hello/1/2/3
           echo "sessionToken" > ./hello/1/2/3/hello.txt
           echo "token=$(cat ./hello/1/2/3/hello.txt)" >> "$GITHUB_OUTPUT"
           echo "::add-mask::sessiontoken=$(cat ./hello/1/2/3/hello.txt)" >> "$GITHUB_OUTPUT"
 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2:  ${{needs.job1.outputs.output2}}
        run: | 
            echo "$OUTPUT1"
            echo "$OUTPUT2"
            echo "$OUTPUT1" > token.txt
            cat token.txt

      - name: Upload Session Token in case of failure
        uses: actions/upload-artifact@v4
        with:
          name: Session Token
          path: token.txt

   
  
