name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", pypy-2.7, pypy-3.8]
        exclude:
          - os: macos-latest
            python-version: "3.7"
            python-version: "3.8"
            python-version: "3.9"
            python-version: "pypy-2.7"
            python-version: "pypy-3.8"
          - os: windows-latest
            python-version: "3.7"
    steps:
        - uses: actions/checkout@v3
        - run: python --version
        
