name: Python package

on: 
 push:
  branches:
   - main

jobs:
  build:

    runs-on: ubuntu-latest
   

    steps:
      - uses: actions/checkout@v3
     
      - name: Generate IAM Credential Report with retry
        run: |
            for i in {1..5}; do
              cat heelo.txt
              if [ $? -eq 0 ]; then
                echo "Credential report generated successfully"
              else
                echo "Failed to generate credential report. Retrying..."
              fi
            done
            if [ $i -eq 5 ]; then
              echo "Failed to generate credential report after 5 retries"
              exit 1
            fi
      
#       - name: version compatability
#         if: ${{ steps.pyhton-version.outputs.version != '3.7' }}
#         run: python --version
