name: tools
env:
  version3.7: 3.7
  version3.8: 3.8
  version3.9: 3.9
  version3.10: 3.10
on:
 workflow_dispatch:
   inputs:
     version:
      type: choice
      description: select py version
      options: 
        - ${{ env.version3.7 }}
        - ${{ env.version3.8 }}
        - ${{ env.version3.9 }}
        - ${{ env.version3.10 }}
    
     environment:
        type: dev

jobs:
 tools:
  name: tools
  runs-on: ubuntu-latest
  steps:
   - name: code checkout
     uses: actions/checkout@v3
   - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v4
     with:
        python-version: ${{ github.event.inputs.py-version }}
   - name: install dependencies
     run: pip install requirements.txt
