name: Python package

on: 
 push:
  branches:
   - main

jobs:
  build:

    runs-on: ubuntu-latest
   

    steps:
      - uses: actions/checkout@v3
     
      - name: Generate IAM Credential Report with retry
        run: |
            for i in {1..5}; do
              echo "Attempt $i to generate IAM report..."
              cat hello.txt && break
              [[ $i -lt 5 ]] && sleep 10 || { echo "Max retries reached. Exiting..."; exit 1; }
            done
      
#       - name: version compatability
#         if: ${{ steps.pyhton-version.outputs.version != '3.7' }}
#         run: python --version
