name: tools
env:
  versionone: '3.7'
  versiontwo: '3.8'
  versionthree: '3.9'
  versionten: '3.10'
on:
 workflow_dispatch:
   inputs:
     version:
      type: string
      description: select py version
      
    
     environment:
        type: dev

jobs:
 tools:
  name: tools
  runs-on: ubuntu-latest
  steps:
   - name: code checkout
     uses: actions/checkout@v3
   - name: Set up Python 
     uses: actions/setup-python@v4
     with:
        python-version: ${{ github.event.inputs.version }}
   - name: install dependencies
     run: pip install requirements.txt
