on: 
 push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: Create file
        run: |
         echo "Hello, World! ewrw" > example.txt
         wget https://get.jenkins.io/war-stable/2.479.1/jenkins.war
         cp Dockerfile swapfile
      - name: Cache file
        uses: actions/cache@v3
        with:
          path: |
           example.txt
           jenkins.war
           swapfile
          key: my-cache-key
          # Optionally set restore-keys for fallback if needed

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: Restore cached file
        uses: actions/cache@v3
        with:
          path: | 
             example.txt
             jenkins.war
             swapfile
          key: my-cache-key
      - name: Access shared file
        run: |
          cat example.txt
          ls -al
          cat swapfile

