name: artifacr url
on: 
 workflow_dispatch: {}
jobs:
 url:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@main
     - name: Upload artifact
       id: artifact-upload-step
       uses: actions/upload-artifact@v4
       with:
          name: my-artifact
          path: .
     - name: Generate artifact URL
       run: |
        echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
        echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
       env:
        GH_TOKEN: ${{ github.token }}
