name: artifacr url
on: 
 workflow_dispatch: {}
jobs:
 url:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@main
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
          name: my-artifact
          path: .
     - name: Generate artifact URL
       run: |
        echo "Artifact URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/" >> $GITHUB_ENV
        
