name: artifacr url
on: 
 workflow_dispatch: {}
jobs:
 url:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@main
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
          name: my-artifact
          path: .
     - name: Generate artifact URL
       run: |
        gh run view ${{ github.run_id }} --json artifacts -q '.artifacts.[].archiveDownloadUrl' > artifact_links.txt
        cat artifact_links.txt
       env:
        GH_TOKEN: ${{ github.token }}
